apiVersion: cloudresource.keikoproj.io/v1alpha1
kind: CloudResourceDeployment
metadata:
  name: cloudresourcedeployment-ec2
spec:
  cloudformation:
    # Add fields here
    stackname: "cloudresource-ec2"
    assumeroleprovider:
      acctnum: '586597078518'
      env: ppd
      roleSessionName: gitops-deployment
    tags:
        cfn-ctrl: "true" 
    parameters:
        AMIid: "ami-0800fc0fa715fdcfe"
        InstanceType: "m5.xlarge"
    template: |
        ---
         AWSTemplateFormatVersion: '2010-09-09'
         Description: Dummy EC2
         Parameters:
           InstanceType:
             Description: EC2 instance sizes.
             Type: String
             ConstraintDescription: must be a valid EC2 instance type that supports the chosen
               AMI.
           AMIid:
             Type: String
             Description: 'Use the latest HVM AMI ID from the AMI Catalog: amiCatalog'
         Resources:
           LinuxEC2Instance:
             Type: AWS::EC2::Instance
             Properties:
               ImageId:
                 Ref: AMIid
               InstanceType:
                 Ref: InstanceType
